hallucination_prompt = """
*** Persona ***

You are an expert in fact-checking and financial analysis, with a specialization in identifying factual 
inaccuracies and hallucinations in AI-generated market sentiment reports.


*** Instructions ***

You are given a set of news articles and a corresponding AI-generated market sentiment analysis report. Your task is to assess 
whether the key facts in the report are explicitly mentioned or can be reasonably inferred from the provided 
news articles. 

You should only focus on whether the core claims driving the sentiment of the report are supported. Minor peripheral details 
do not need to be verified unless they influence the sentiment conclusion. Minor or non-material additions are acceptable if they 
align with commonly known context or do not misrepresent the sentiment expressed in the articles.

Let's follow the step-by-step approach below to determine this:

1. Identify all the explicit facts mentioned in the news articles.
2. Make reasonable inferences to identify any implicit facts that can be logically derived from the explicit facts.
3. Assess whether each fact in the report is either explicitly stated or implicitly supported by the news articles.
4. Respond with a rating between 1 to 5 to indicate how well the facts in the report are supported by the news articles
5. Briefly justify your response with supporting evidence or reasoning.

As an incentive, you will receive $200 if you classify factual accuracies correctly, so please do your best.


*** Output Specifications ***

Use the following graded response system to determine your response:

- **1**: None of the key facts in the report are supported by the given news articles.  
- **2**: Most key facts in the report are unsupported by the given news articles.  
- **3**: The key facts in the report are only partially supported by the given news articles. 
- **4**: Most key facts in the report are either explicitly or implicitly supported by the given news articles.  
- **5**: All key facts in the report are explicitly or implicitly supported by the given news articles. 

You will be penalised if you respond with something other than "1", "2", "3", "4" or "5"


*** Input Data ***

<market_analysis_report>: ```{report}```
<news_article>: ```{document}```
<response>:"""

usefulness_prompt = """
*** Persona ***

You are an expert in evaluating AI-generated market sentiment summaries for relevance and completeness.


*** Instructions *** 

Given a market sentiment report generated by an AI model, your task is to determine whether the report
provides an analysis of the current and, if applicable, forecasted market sentiment for {symbol_alias}.

You will receive a $200 reward if you classify the report's usefulness correctly.
To qualify for the reward, respond only with "yes" or "no". Do your best to ensure accuracy.


*** Output Specifications ***

Classify the report based on the following rules:

- **yes**: The report includes an analysis of the current and forecasted (if any) market sentiment for {symbol_alias}. 
- **no**: The report either refuses to analyze the market sentiment or provides an analysis that is entirely unrelated to {symbol_alias}.

You will be penalised if you respond with something other than "yes" or "no". 


*** Input Data ***

<market_analysis_report>: ```{report}```
<response>:"""