BINANCE: 
  Bitcoin: BTCUSDT
  Ethereum: ETHUSDT
  Ripple: XRPUSDT
  Binance Coin: BNBUSDT
  Solana: SOLUSDT
  Chainlink: LINKUSDT
NASDAQ:
  Meta: META
  Nvidia : NVDA
  Tesla : TSLA
  Palantir: PLTR
  Microsoft : MSFT
  Alphabet (Google) : GOOGL